grpc:
  enable-reflection: true

spring:
  datasource:
    url: jdbc:mysql://localhost/testdb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
   hibernate.ddl-auto: update